### PR TITLE
Travis-ci integ test running.. with lots of docker

### PR DESCRIPTION
**Pull request by euank**
I will be absolutely amazed if this runs.

### CODE REVIEW

**Comment by euank** [comment]
Well, it passed for the stable branch and the nightly branch flaked in a way that honestly looks like a transient crates.io error or travis error. Everything went much better than expected!

:tada: 

Feel free to review this franken-test-machine @ianweller

**Comment by euank** [comment]
I would like to merge this with roughly the scope it is now just because it gets the infra in place and I'd rather iterate on the test itself not sucking separately.

**Comment by iliana** [comment]
Is it assumed that the only tests run by `cargo test` are integration tests?

If not, having integ tests behind `#[cfg(feature = "test-integ")]` would be nice.

**Review by iliana — APPROVED** [review]

**Comment by euank** [comment]
Good call on the feature-flag, willdo

**Comment by euank** [comment]
Woo, green! ... `test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured`. Oh. For some reason the `cargo test` command it runs isn't what I have in the .travis.yml, chalk it up to a bug on their end...

**Comment by euank** [comment]
> test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

Yup, one no-op push later and it's happy. Merging

**Pull request merged**
